---
abstract: 'map paths to handlers'
author:
  - 'Matt Lawrence <mattlaw@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Path-Mapper
provides:
  Path::Mapper:
    file: lib/Path/Mapper.pm
    version: 0.01
  Path::Mapper::Match:
    file: lib/Path/Mapper/Match.pm
requires:
  List::Util: 0
  perl: v5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
